# Generated by Django 5.1.3 on 2024-11-09 05:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('original_title', models.TextField()),
                ('title', models.TextField()),
                ('budget', models.BigIntegerField()),
                ('genre', models.JSONField()),
                ('homepage', models.TextField()),
                ('keywords', models.JSONField()),
                ('original_language', models.CharField(max_length=2)),
                ('overview', models.TextField()),
                ('popularity', models.FloatField()),
                ('production_companies', models.JSONField()),
                ('production_countries', models.JSONField()),
                ('release_date', models.DateField(null=True)),
                ('revenue', models.BigIntegerField()),
                ('runtime', models.FloatField()),
                ('spoken_languages', models.JSONField()),
                ('status', models.CharField(max_length=15)),
                ('tagline', models.TextField()),
                ('vote_average', models.FloatField()),
                ('vote_count', models.IntegerField()),
                ('poster_path', models.TextField()),
            ],
        ),
    ]
