# Generated by Django 5.1.3 on 2024-11-09 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRcmdApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MoviePosters',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('backdrop_path', models.TextField()),
                ('backdrop_sizes', models.JSONField()),
                ('poster_path', models.TextField()),
                ('poster_size', models.JSONField()),
            ],
        ),
        migrations.DeleteModel(
            name='Movie',
        ),
    ]
