# Generated by Django 5.1.3 on 2024-11-09 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRcmdApp', '0002_movieposters_delete_movie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movieposters',
            name='backdrop_sizes',
        ),
        migrations.RemoveField(
            model_name='movieposters',
            name='poster_size',
        ),
    ]
