# Generated by Django 5.1.3 on 2024-11-09 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MovieRcmdApp', '0003_remove_movieposters_backdrop_sizes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieposters',
            name='backdrop_path',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='movieposters',
            name='poster_path',
            field=models.TextField(null=True),
        ),
    ]
